const RegisterActionTypes = ({
  CONFIRM_LESSON_REGISTRATION: 'CONFIRM_LESSON_REGISTRATION',
  ADD_LESSON_TO_PENDING: 'ADD_LESSON_TO_PENDING',
  REGISTER_PENDING_LESSONS: 'REGISTER_PENDING_LESSONS',
  INCREMENT_LESSONS_PER_WEEK: 'INCREMENT_LESSONS_PER_WEEK',
  REMOVE_LESSON_FROM_REGISTER: 'REMOVE_LESSON_FROM_REGISTER',
  DECREMENT_LESSONS_PER_WEEK: 'DECREMENT_LESSONS_PER_WEEK',
  UPDATE_REGISTERED_STATUS: 'UPDATE_REGISTERED_STATUS'
});

export default RegisterActionTypes;
