const RegisterActionTypes = ({
  ADD_LESSON_TO_REGISTER: 'ADD_LESSON_TO_REGISTER',
  INCREMENT_LESSONS_PER_WEEK: 'INCREMENT_LESSONS_PER_WEEK',
  REMOVE_LESSON_FROM_REGISTER: 'REMOVE_LESSON_FROM_REGISTER',
  DECREMENT_LESSONS_PER_WEEK: 'DECREMENT_LESSONS_PER_WEEK'
});

export default RegisterActionTypes;
