const RegisterActionTypes = ({
  INCREMENT_LESSONS_PER_WEEK: 'INCREMENT_LESSONS_PER_WEEK',
  DECREMENT_LESSONS_PER_WEEK: 'DECREMENT_LESSONS_PER_WEEK',
  CONFIRM_REGISTRATION: 'CONFIRM_REGISTRATION',
  UPDATE_REGISTER_ADD_PENDING: 'UPDATE_REGISTER_ADD_PENDING',
  ADD_PENDING_REGISTRATION: 'ADD_PENDING_REGISTRATION',
  ADD_PENDING_UNREGISTRATION: 'ADD_PENDING_UNREGISTRATION',
  UPDATE_REGISTER_REMOVE_PENDING: 'UPDATE_REGISTER_REMOVE_PENDING',
  REMOVE_PENDING_REGISTRATION: 'REMOVE_PENDING_REGISTRATION',
  REMOVE_PENDING_UNREGISTRATION: 'REMOVE_PENDING_UNREGISTRATION',
  REGISTER_PENDING_LESSONS: 'REGISTER_PENDING_LESSONS',
  UNREGISTER_PENDING_LESSONS: 'UNREGISTER_PENDING_LESSONS',
  UPDATE_REGISTERED_STATUS: 'UPDATE_REGISTERED_STATUS',
  CLEAR_PENDING_DATA: 'CLEAR_PENDING_DATA'
});

export default RegisterActionTypes;
