const DirectoryActionTypes = ({
  FETCH_DIRECTORY_DATA_START: 'FETCH_DIRECTORY_DATA_START',
  FETCH_DIRECTORY_DATA_SUCCESS: 'FETCH_DIRECTORY_DATA_SUCCESS',
  FETCH_DIRECTORY_DATA_FAILURE: 'FETCH_DIRECTORY_DATA_FAILURE'
});

export default DirectoryActionTypes;
