const LessonActionTypes = ({
  TOGGLE_LESSON_HIDDEN: 'TOGGLE_LESSON_HIDDEN',
  SET_LESSON_HIDDEN: 'SET_LESSON_HIDDEN',
  SET_LESSON_DATA: 'SET_LESSON_DATA',
  SET_DEFAULT_DAY_OF_WEEK: 'SET_DEFAULT_DAY_OF_WEEK',
  UPDATE_DAY_OF_WEEK: 'UPDATE_DAY_OF_WEEK'
});

export default LessonActionTypes;