const LessonActionTypes = ({
  TOGGLE_LESSON_HIDDEN: 'TOGGLE_LESSON_HIDDEN',
  SET_LESSON_DATA: 'SET_LESSON_DATA',
  SET_DEFAULT_DAY_OF_WEEK: 'SET_DEFAULT_DAY_OF_WEEK',
  UPDATE_DAY_OF_WEEK: 'UPDATE_DAY_OF_WEEK',
  FETCH_LESSON_DATA_START: 'FETCH_LESSON_DATA_START',
  FETCH_LESSON_DATA_SUCCESS: 'FETCH_LESSON_DATA_SUCCESS',
  FETCH_LESSON_DATA_FAILURE: 'FETCH_LESSON_DATA_FAILURE',
  VIEW_LESSON_TIMES: 'VIEW_LESSON_TIMES',
  CLOSE_LESSON_TIMES: 'CLOSE_LESSON_TIMES',
  CLEAR_LESSON_DATA: 'CLEAR_LESSON_DATA'
})

export default LessonActionTypes;